name: Protocoller
version: '${project.version}'
main: net.alis.protocoller.plugin.ProtocollerPlugin
api-version: 1.13
load: STARTUP
authors: [ ALis ]
description: A simple minecraft packets sniffer
website: https://vk.com/alphatwo
